# Generated by Django 5.2.1 on 2025-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
